### ISSUE TITLE
Feature Set

### ISSUE THREAD

**Issue by AitchGrasso** [snowballDevs/kandoo#5]

**Comment by IntelliJinceTech** [comment]
This will become outdated if we implement the "advanced" organization of file structure since it contains a feature folder. 

In the meantime, I can create a backlog of features that we want to cover for our MVP (this would just be a copy-paste from our Miro board into GitHub) and we can decide what we need to focus on first in order to achieve said features. 

Thoughts? @AitchGrasso @isomer04 @mjbramich @Michelle-932
